# Generated by Django 4.2.30 on 2026-07-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('objet', models.CharField(max_length=200)),
                ('quantite', models.IntegerField(default=0)),
                ('categorie', models.CharField(max_length=100)),
                ('emplacement', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
