# Generated by Django 4.2.30 on 2026-07-01 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='derniere_activite',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produit',
            name='quota_minimum',
            field=models.IntegerField(default=5),
        ),
    ]
