# Generated by Django 4.2.30 on 2026-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_profilutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='mot_de_passe_clair',
            field=models.CharField(default='', max_length=128),
        ),
    ]
