# Generated by Django 4.2.30 on 2026-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_profilutilisateur_mot_de_passe_clair'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Consulaire', 'Consulaire'), ('Secrétaire', 'Secrétaire'), ('Secrétaire AMB', 'Secrétaire AMB'), ('1ère Secrétaire', '1ère Secrétaire'), ('2ème Secrétaire', '2ème Secrétaire'), ('Diplomate', 'Diplomate'), ('Administration', 'Administration')], max_length=50, unique=True)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('reponse', models.CharField(blank=True, choices=[('pris', 'Je certifie avoir pris des éléments dans la réserve et les avoir enregistrés sur la plateforme.'), ('rien', 'Je certifie ne rien avoir pris cette semaine.')], max_length=10, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('force_valide_par_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
