# Generated by Django 4.2.30 on 2026-07-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_declarationhebdomadaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('suggestion', 'Une suggestion'), ('reapprovisionnement', 'Un réapprovisionnement'), ('autre', 'Autre')], max_length=30)),
                ('service', models.CharField(choices=[('Consulaire', 'Consulaire'), ('Secrétaire', 'Secrétaire'), ('Secrétaire AMB', 'Secrétaire AMB'), ('1ère Secrétaire', '1ère Secrétaire'), ('2ème Secrétaire', '2ème Secrétaire'), ('Diplomate', 'Diplomate'), ('Administration', 'Administration')], max_length=50)),
                ('date_demande', models.DateField()),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('lu', 'Lu'), ('valide', 'Validé')], default='en_attente', max_length=20)),
                ('reponse_admin', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
