# Generated by Django 4.2.30 on 2026-07-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_demandeservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fichier_facture', models.FileField(upload_to='factures/')),
            ],
        ),
    ]
