# Generated by Django 4.2.30 on 2026-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='acces_factures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='acces_gestion_demandes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='acces_gestion_utilisateurs',
            field=models.BooleanField(default=False),
        ),
    ]
