# Generated by Django 4.2.30 on 2026-07-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_profilutilisateur_acces_factures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='type_profil',
            field=models.CharField(default='services', max_length=20),
        ),
    ]
