# Generated by Django 4.2.30 on 2026-07-05 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_profilutilisateur_type_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('objet', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('service', models.CharField(default='Administration', max_length=100)),
                ('date_mouvement', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
