# Generated by Django 4.2.30 on 2026-07-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_mouvementstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementstock',
            name='reference',
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='config.produit'),
        ),
    ]
